import { CvssTemplate } from "./types";

/**
 * ~40-50 scenario presets across the 14 VulnType families (vulnTypes.ts). Selecting one in the
 * UI fills every CVSS 3.1 + 4.0 metric plus the OWASP/VRT/CWE/reference ids in one shot,
 * mirroring lib/msfvenom/templates.ts's template→custom flow.
 *
 * CVSS 4.0's Threat metric (E) is always "X" here — Exploit Maturity is an engagement-specific
 * input the user layers on top of a template, not a property of the vulnerability scenario
 * itself (see CvssCalculatorTool.tsx: E is exempt from resetToCustom for the same reason).
 */
export const CVSS_TEMPLATES: CvssTemplate[] = [
  // ---- xss ----
  {
    id: "xss-reflected-web",
    vulnTypeId: "xss",
    label: "Reflected XSS — session cookie theft (no HttpOnly)",
    platforms: ["web"],
    description:
      "A crafted link reflects unsanitized input into the page, executing attacker JS in the victim's browser. No HttpOnly flag lets the payload read the session cookie.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "R", S: "C", C: "L", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "P", VC: "L", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "xss-reflected",
    cweId: "CWE-79",
    references: [
      { label: "PortSwigger — Cross-site scripting", url: "https://portswigger.net/web-security/cross-site-scripting" },
      { label: "OWASP Cheat Sheet — XSS Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "xss-stored-web",
    vulnTypeId: "xss",
    label: "Stored XSS — fires against every viewer, including admins",
    platforms: ["web"],
    description:
      "A low-privileged user posts a payload (e.g. in a comment or profile field) that executes against anyone who later views it, including administrators — no click required beyond viewing the page.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "xss-stored",
    cweId: "CWE-79",
    references: [
      { label: "PortSwigger — Cross-site scripting", url: "https://portswigger.net/web-security/cross-site-scripting" },
      { label: "OWASP Cheat Sheet — XSS Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "xss-dom-web",
    vulnTypeId: "xss",
    label: "DOM-based XSS — client-side sink, no server round trip",
    platforms: ["web"],
    description:
      "Attacker-controlled data (e.g. a URL fragment) flows into a dangerous client-side sink like innerHTML entirely in the browser, without the server ever seeing the payload.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "R", S: "C", C: "L", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "P", VC: "L", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "xss-dom",
    cweId: "CWE-79",
    references: [
      { label: "PortSwigger — Cross-site scripting", url: "https://portswigger.net/web-security/cross-site-scripting" },
      { label: "OWASP Cheat Sheet — XSS Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "xss-api-json-reflected",
    vulnTypeId: "xss",
    label: "API-reflected XSS — unsanitized field rendered by a downstream client",
    platforms: ["api"],
    description:
      "An API echoes an unsanitized field (e.g. an error message) back in a JSON response; a client application renders it unsafely, executing the payload in that client's context.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "R", S: "C", C: "L", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "P", VC: "L", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "xss-reflected",
    cweId: "CWE-79",
    references: [
      { label: "PortSwigger — Cross-site scripting", url: "https://portswigger.net/web-security/cross-site-scripting" },
      { label: "OWASP Cheat Sheet — XSS Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "xss-mobile-webview",
    vulnTypeId: "xss",
    label: "WebView XSS — JS bridge exposes native functionality",
    platforms: ["mobile"],
    description:
      "A mobile app's WebView renders attacker-influenced content; a misconfigured JavaScript bridge lets the resulting script call native app functions and read device data.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "R", S: "C", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "P", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "mobile-m4-input-output-validation",
    vrtRefId: "xss-reflected",
    cweId: "CWE-79",
    references: [
      { label: "PortSwigger — Cross-site scripting", url: "https://portswigger.net/web-security/cross-site-scripting" },
      { label: "OWASP Mobile Top 10 2024 — M4 Insufficient Input/Output Validation", url: "https://owasp.org/www-project-mobile-top-10/2023-risks/m4-insufficient-input-output-validation.html" },
    ],
  },

  // ---- sqli ----
  {
    id: "sqli-auth-bypass",
    vulnTypeId: "sqli",
    label: "SQL injection — authentication bypass",
    platforms: ["web", "api"],
    description: "A classic ' OR 1=1-- style payload in the login form bypasses authentication entirely, logging the attacker in as any user.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "sqli-generic",
    cweId: "CWE-89",
    references: [
      { label: "PortSwigger — SQL injection", url: "https://portswigger.net/web-security/sql-injection" },
      { label: "OWASP Cheat Sheet — SQL Injection Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "sqli-union-data-extraction",
    vulnTypeId: "sqli",
    label: "SQL injection — UNION-based full database dump",
    platforms: ["web", "api"],
    description: "A UNION SELECT payload in a vulnerable query parameter dumps arbitrary tables, including other users' data and credentials.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "sqli-generic",
    cweId: "CWE-89",
    references: [
      { label: "PortSwigger — SQL injection", url: "https://portswigger.net/web-security/sql-injection" },
      { label: "OWASP Cheat Sheet — SQL Injection Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "sqli-blind-boolean-time",
    vulnTypeId: "sqli",
    label: "SQL injection — blind boolean/time-based",
    platforms: ["web", "api"],
    description:
      "No query output is returned directly; data is exfiltrated one bit at a time via true/false or timing (SLEEP()) responses. Heavy time-based queries can also degrade database availability.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "L" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "L", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "sqli-generic",
    cweId: "CWE-89",
    references: [
      { label: "PortSwigger — SQL injection", url: "https://portswigger.net/web-security/sql-injection" },
      { label: "OWASP Cheat Sheet — SQL Injection Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "sqli-second-order",
    vulnTypeId: "sqli",
    label: "Second-order SQL injection",
    platforms: ["web", "api"],
    description:
      "A payload stored benignly in one feature (e.g. a display name) is later concatenated unsafely into a different, downstream query (e.g. an admin report), triggering injection there.",
    cvss31: { AV: "N", AC: "H", PR: "L", UI: "N", S: "C", C: "H", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "L", UI: "N", VC: "H", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "sqli-generic",
    cweId: "CWE-89",
    references: [
      { label: "PortSwigger — SQL injection", url: "https://portswigger.net/web-security/sql-injection" },
      { label: "OWASP Cheat Sheet — SQL Injection Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html" },
    ],
  },

  // ---- idor ----
  {
    id: "idor-web-account-takeover",
    vulnTypeId: "idor",
    label: "IDOR — edit another user's account via a guessable ID",
    platforms: ["web"],
    description: "Changing a user_id parameter lets an authenticated attacker view and modify another user's account, including email/password reset.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "idor",
    cweId: "CWE-639",
    references: [
      { label: "PortSwigger — Insecure direct object references (IDOR)", url: "https://portswigger.net/web-security/access-control/idor" },
      { label: "PortSwigger — Top 10 API vulnerabilities", url: "https://portswigger.net/web-security/api-testing/top-10-api-vulnerabilities" },
    ],
  },
  {
    id: "idor-api-object-access",
    vulnTypeId: "idor",
    label: "IDOR — read-only access to another user's API object",
    platforms: ["api"],
    description: "An authenticated API request for a sequential/guessable object ID (e.g. /api/orders/{id}) returns another user's private data.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api1-bola",
    vrtRefId: "idor",
    cweId: "CWE-639",
    references: [
      { label: "PortSwigger — Insecure direct object references (IDOR)", url: "https://portswigger.net/web-security/access-control/idor" },
      { label: "PortSwigger — Top 10 API vulnerabilities", url: "https://portswigger.net/web-security/api-testing/top-10-api-vulnerabilities" },
    ],
  },
  {
    id: "idor-mobile-api-unauthenticated",
    vulnTypeId: "idor",
    label: "IDOR — mobile backend API with no auth check at all",
    platforms: ["mobile", "api"],
    description: "The API backing a mobile app never validates that the caller owns the requested object ID, and requires no authentication token either.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api1-bola",
    vrtRefId: "idor",
    cweId: "CWE-639",
    references: [
      { label: "PortSwigger — Insecure direct object references (IDOR)", url: "https://portswigger.net/web-security/access-control/idor" },
      { label: "PortSwigger — Top 10 API vulnerabilities", url: "https://portswigger.net/web-security/api-testing/top-10-api-vulnerabilities" },
    ],
  },

  // ---- broken-access-control ----
  {
    id: "bac-vertical-privesc-admin-panel-web",
    vulnTypeId: "broken-access-control",
    label: "Vertical privilege escalation — regular user reaches admin functionality (web app)",
    platforms: ["web"],
    description: "A missing server-side role check lets any authenticated user invoke admin-only endpoints directly, gaining full administrative capability.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP Top 10 2021 — A01 Broken Access Control", url: "https://owasp.org/Top10/2021/A01_2021-Broken_Access_Control/" },
    ],
  },
  {
    id: "bac-vertical-privesc-admin-panel-api",
    vulnTypeId: "broken-access-control",
    label: "Vertical privilege escalation — regular user reaches admin-only API endpoint",
    platforms: ["api"],
    description: "A missing server-side role check lets any authenticated user invoke admin-only API endpoints directly, gaining full administrative capability. Matches API5:2023's function-level authorization gap exactly.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api5-bfla",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP API Security Top 10 2023 — API5 Broken Function Level Authorization", url: "https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/" },
    ],
  },
  {
    id: "bac-horizontal-privesc-web",
    vulnTypeId: "broken-access-control",
    label: "Horizontal privilege escalation — act as another same-tier user (web app)",
    platforms: ["web"],
    description: "An authenticated user can perform write actions on another peer user's data or settings, not just read them (distinct from a read-only IDOR).",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP Top 10 2021 — A01 Broken Access Control", url: "https://owasp.org/Top10/2021/A01_2021-Broken_Access_Control/" },
    ],
  },
  {
    id: "bac-horizontal-privesc-api",
    vulnTypeId: "broken-access-control",
    label: "Horizontal privilege escalation — act as another same-tier user via the API",
    platforms: ["api"],
    description: "An authenticated API caller can perform write actions on another peer user's object, not just read it — an object-level authorization gap (BOLA), just triggered via a write rather than a read.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api1-bola",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP API Security Top 10 2023 — API1 Broken Object Level Authorization", url: "https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/" },
    ],
  },
  {
    id: "bac-forced-browsing-unauth-endpoint-web",
    vulnTypeId: "broken-access-control",
    label: "Forced browsing — sensitive web endpoint has no auth check",
    platforms: ["web"],
    description: "An unlinked but guessable/discoverable endpoint (e.g. /admin/export) performs no authentication check at all and returns sensitive data to anyone.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP Top 10 2021 — A01 Broken Access Control", url: "https://owasp.org/Top10/2021/A01_2021-Broken_Access_Control/" },
    ],
  },
  {
    id: "bac-forced-browsing-unauth-endpoint-api",
    vulnTypeId: "broken-access-control",
    label: "Forced browsing — sensitive API endpoint has no auth check",
    platforms: ["api"],
    description: "An undocumented but guessable/discoverable API endpoint (e.g. /api/admin/export) performs no authentication check at all and returns sensitive data to anyone. A missing function-level permission check, per API5:2023.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api5-bfla",
    vrtRefId: "broken-access-control",
    cweId: "CWE-284",
    references: [
      { label: "PortSwigger — Access control vulnerabilities", url: "https://portswigger.net/web-security/access-control" },
      { label: "OWASP API Security Top 10 2023 — API5 Broken Function Level Authorization", url: "https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/" },
    ],
  },

  // ---- ssrf ----
  {
    id: "ssrf-cloud-metadata-credential-theft-web",
    vulnTypeId: "ssrf",
    label: "SSRF — cloud metadata endpoint reached, IAM credentials stolen (web app)",
    platforms: ["web"],
    description:
      "A URL-fetching feature is abused to reach the cloud provider's instance metadata service (e.g. 169.254.169.254), stealing IAM credentials that grant access well beyond the vulnerable app itself.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "H", SA: "N", E: "X" },
    owaspRefId: "web-a10-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP Cheat Sheet — SSRF Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ssrf-cloud-metadata-credential-theft-api",
    vulnTypeId: "ssrf",
    label: "SSRF — cloud metadata endpoint reached via an API parameter, IAM credentials stolen",
    platforms: ["api"],
    description:
      "An API's URL-fetching parameter (e.g. a webhook or import-from-URL feature) is abused to reach the cloud provider's instance metadata service, stealing IAM credentials that grant access well beyond the vulnerable API itself. Matches API7:2023 exactly.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "H", SA: "N", E: "X" },
    owaspRefId: "api-api7-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP API Security Top 10 2023 — API7 Server Side Request Forgery", url: "https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/" },
    ],
  },
  {
    id: "ssrf-internal-port-scan-web",
    vulnTypeId: "ssrf",
    label: "SSRF — internal network/service reconnaissance (web app)",
    platforms: ["web"],
    description: "The same URL-fetching feature is used to reach internal-only services and admin interfaces not otherwise exposed to the internet.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a10-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP Cheat Sheet — SSRF Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ssrf-internal-port-scan-api",
    vulnTypeId: "ssrf",
    label: "SSRF — internal network/service reconnaissance via an API parameter",
    platforms: ["api"],
    description: "An API's URL-fetching parameter is used to reach internal-only services and admin interfaces not otherwise exposed to the internet.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api7-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP API Security Top 10 2023 — API7 Server Side Request Forgery", url: "https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/" },
    ],
  },
  {
    id: "ssrf-blind-oob-web",
    vulnTypeId: "ssrf",
    label: "Blind SSRF — confirmed only via out-of-band callback (web app)",
    platforms: ["web"],
    description: "No response is returned to the attacker; the request is only confirmed via an out-of-band DNS/HTTP interaction, limiting but not eliminating impact.",
    cvss31: { AV: "N", AC: "H", PR: "L", UI: "N", S: "C", C: "L", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "L", UI: "N", VC: "N", VI: "L", VA: "N", SC: "L", SI: "L", SA: "N", E: "X" },
    owaspRefId: "web-a10-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP Cheat Sheet — SSRF Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ssrf-blind-oob-api",
    vulnTypeId: "ssrf",
    label: "Blind SSRF via an API parameter — confirmed only via out-of-band callback",
    platforms: ["api"],
    description: "No response is returned to the attacker; the request from a vulnerable API parameter is only confirmed via an out-of-band DNS/HTTP interaction, limiting but not eliminating impact.",
    cvss31: { AV: "N", AC: "H", PR: "L", UI: "N", S: "C", C: "L", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "L", UI: "N", VC: "N", VI: "L", VA: "N", SC: "L", SI: "L", SA: "N", E: "X" },
    owaspRefId: "api-api7-ssrf",
    vrtRefId: "ssrf",
    cweId: "CWE-918",
    references: [
      { label: "PortSwigger — Server-side request forgery (SSRF)", url: "https://portswigger.net/web-security/ssrf" },
      { label: "OWASP API Security Top 10 2023 — API7 Server Side Request Forgery", url: "https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/" },
    ],
  },

  // ---- csrf ----
  {
    id: "csrf-state-changing-action",
    vulnTypeId: "csrf",
    label: "CSRF — unauthorized state-changing action (no anti-CSRF token)",
    platforms: ["web"],
    description: "A state-changing endpoint (e.g. change email) lacks an anti-CSRF token; a malicious page auto-submits a forged request using the victim's active session.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "R", S: "U", C: "N", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "P", VC: "N", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "csrf",
    cweId: "CWE-352",
    references: [
      { label: "PortSwigger — Cross-site request forgery (CSRF)", url: "https://portswigger.net/web-security/csrf" },
      { label: "OWASP Cheat Sheet — CSRF Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "csrf-account-takeover",
    vulnTypeId: "csrf",
    label: "CSRF chained to full account takeover",
    platforms: ["web"],
    description: "CSRF on the password-change or email-linking flow is chained into a complete account takeover, not just a single unwanted action.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "R", S: "C", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "P", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "csrf",
    cweId: "CWE-352",
    references: [
      { label: "PortSwigger — Cross-site request forgery (CSRF)", url: "https://portswigger.net/web-security/csrf" },
      { label: "OWASP Cheat Sheet — CSRF Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html" },
    ],
  },

  // ---- sensitive-data-exposure ----
  {
    id: "sde-web-sensitive-data-in-url",
    vulnTypeId: "sensitive-data-exposure",
    label: "Sensitive data passed in the URL — leaks via history, logs, and Referer",
    platforms: ["web"],
    description: "A session token, password-reset code, or API key is passed as a GET query-string parameter instead of a header/cookie/POST body, leaking into browser history, server access logs, and the Referer header sent to third-party resources on the page.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a02-crypto-failures",
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-200",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Top 10 2021 — A02 Cryptographic Failures", url: "https://owasp.org/Top10/2021/A02_2021-Cryptographic_Failures/" },
    ],
  },
  {
    id: "sde-api-excessive-data-exposure",
    vulnTypeId: "sensitive-data-exposure",
    label: "API excessive data exposure — full object returned, not just displayed fields",
    platforms: ["api"],
    description: "An API endpoint returns the entire backing object (e.g. password hash, SSN) even though the client UI only displays a subset of it.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api3-bopla",
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-200",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Top 10 2021 — A02 Cryptographic Failures", url: "https://owasp.org/Top10/2021/A02_2021-Cryptographic_Failures/" },
    ],
  },
  {
    id: "sde-hardcoded-secrets-desktop-windows",
    vulnTypeId: "sensitive-data-exposure",
    label: "Hardcoded API keys/credentials in a Windows desktop binary",
    platforms: ["desktop-windows"],
    description: "A locally-installed Windows application embeds API keys or credentials directly in its binary/config, extractable via strings or basic reverse engineering, granting access to a separate backend service.",
    cvss31: { AV: "L", AC: "L", PR: "N", UI: "N", S: "C", C: "H", I: "L", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "N", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "L", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-798",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Top 10 2021 — A02 Cryptographic Failures", url: "https://owasp.org/Top10/2021/A02_2021-Cryptographic_Failures/" },
    ],
  },
  {
    id: "sde-unencrypted-storage-mobile",
    vulnTypeId: "sensitive-data-exposure",
    label: "Unencrypted local storage of tokens/PII on a mobile device",
    platforms: ["mobile"],
    description: "The app stores auth tokens or PII in plaintext in local/shared storage, recoverable via physical access to the device.",
    cvss31: { AV: "P", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "P", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "mobile-m9-insecure-data-storage",
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-312",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Mobile Top 10 2024 — M9 Insecure Data Storage", url: "https://owasp.org/www-project-mobile-top-10/2023-risks/m9-insecure-data-storage.html" },
    ],
  },
  {
    id: "sde-config-file-secrets-desktop-linux",
    vulnTypeId: "sensitive-data-exposure",
    label: "World-readable config file with plaintext secrets (Linux)",
    platforms: ["desktop-linux"],
    description: "A configuration file containing plaintext credentials/API keys is left world-readable on a Linux host, extractable by any local low-privileged account.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "N", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-798",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Top 10 2021 — A02 Cryptographic Failures", url: "https://owasp.org/Top10/2021/A02_2021-Cryptographic_Failures/" },
    ],
  },
  {
    id: "sde-plaintext-storage-desktop-mac",
    vulnTypeId: "sensitive-data-exposure",
    label: "Plaintext credentials in a macOS app's preferences file instead of Keychain",
    platforms: ["desktop-mac"],
    description: "A macOS application stores auth tokens or credentials in a plaintext property-list (plist) preferences file instead of the system Keychain, recoverable by any local process or user with file access.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "N", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "sensitive-data-exposure",
    cweId: "CWE-312",
    references: [
      { label: "PortSwigger — Information disclosure", url: "https://portswigger.net/web-security/information-disclosure" },
      { label: "OWASP Top 10 2021 — A02 Cryptographic Failures", url: "https://owasp.org/Top10/2021/A02_2021-Cryptographic_Failures/" },
    ],
  },

  // ---- open-redirect ----
  {
    id: "or-login-redirect-phishing",
    vulnTypeId: "open-redirect",
    label: "Open redirect on login flow, abused for phishing",
    platforms: ["web"],
    description: "An unvalidated redirect parameter on the login/logout flow lets an attacker craft a trusted-looking link that ultimately lands the victim on a phishing page.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "R", S: "U", C: "N", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "P", VC: "N", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "open-redirect",
    cweId: "CWE-601",
    references: [
      { label: "PortSwigger — Open redirection", url: "https://portswigger.net/kb/issues/00500100_open-redirection-reflected" },
      { label: "OWASP Cheat Sheet — Unvalidated Redirects and Forwards", url: "https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html" },
    ],
  },
  {
    id: "or-oauth-redirect-hijack",
    vulnTypeId: "open-redirect",
    label: "Open redirect chained into OAuth authorization code theft",
    platforms: ["web", "api"],
    description: "A permissive redirect_uri validation lets an attacker redirect the OAuth authorization code/token to an attacker-controlled endpoint, enabling account takeover.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "R", S: "C", C: "H", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "P", VC: "H", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "open-redirect",
    cweId: "CWE-601",
    references: [
      { label: "PortSwigger — Open redirection", url: "https://portswigger.net/kb/issues/00500100_open-redirection-reflected" },
      { label: "OWASP Cheat Sheet — Unvalidated Redirects and Forwards", url: "https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html" },
    ],
  },

  // ---- security-misconfiguration ----
  {
    id: "sm-debug-mode-enabled-web",
    vulnTypeId: "security-misconfiguration",
    label: "Debug mode enabled in production (web app)",
    platforms: ["web"],
    description: "A framework's debug mode (e.g. Django DEBUG=True) is left enabled in production, exposing stack traces, source snippets, and configuration secrets on error.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a05-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-489",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP Top 10 2021 — A05 Security Misconfiguration", url: "https://owasp.org/Top10/2021/A05_2021-Security_Misconfiguration/" },
    ],
  },
  {
    id: "sm-debug-mode-enabled-api",
    vulnTypeId: "security-misconfiguration",
    label: "Debug mode enabled in production (API)",
    platforms: ["api"],
    description: "A framework's debug mode is left enabled on a production API host, exposing stack traces, source snippets, and configuration secrets in error responses.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api8-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-489",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP API Security Top 10 2023 — API8 Security Misconfiguration", url: "https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/" },
    ],
  },
  {
    id: "sm-default-credentials-web",
    vulnTypeId: "security-misconfiguration",
    label: "Default/unchanged admin credentials on an exposed web panel",
    platforms: ["web"],
    description: "An exposed admin panel still uses its default/vendor-supplied credentials, giving full administrative control to anyone who tries them.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a05-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-1392",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP Top 10 2021 — A05 Security Misconfiguration", url: "https://owasp.org/Top10/2021/A05_2021-Security_Misconfiguration/" },
    ],
  },
  {
    id: "sm-default-credentials-api",
    vulnTypeId: "security-misconfiguration",
    label: "Default/unchanged admin credentials on an exposed API management interface",
    platforms: ["api"],
    description: "An exposed API management/admin interface still uses its default/vendor-supplied credentials, giving full administrative control to anyone who tries them.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api8-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-1392",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP API Security Top 10 2023 — API8 Security Misconfiguration", url: "https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/" },
    ],
  },
  {
    id: "sm-default-credentials-desktop-linux",
    vulnTypeId: "security-misconfiguration",
    label: "Default/unchanged admin credentials on a local Linux management service",
    platforms: ["desktop-linux"],
    description: "A locally-installed Linux service or agent still uses its default/vendor-supplied credentials on a local management interface, giving full control to any local low-privileged account that tries them.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-1392",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP Top 10 2021 — A05 Security Misconfiguration", url: "https://owasp.org/Top10/2021/A05_2021-Security_Misconfiguration/" },
    ],
  },
  {
    id: "sm-unauthenticated-local-service-desktop-windows",
    vulnTypeId: "security-misconfiguration",
    label: "Unauthenticated local management interface (Windows desktop agent)",
    platforms: ["desktop-windows"],
    description: "A locally-installed Windows agent/service exposes a management or debug interface (e.g. a loopback TCP port) with no authentication of its own, letting any local low-privileged account that can run a process on the box issue privileged commands to it.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-306",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP Top 10 2021 — A05 Security Misconfiguration", url: "https://owasp.org/Top10/2021/A05_2021-Security_Misconfiguration/" },
    ],
  },
  {
    id: "sm-verbose-error-disclosure-web",
    vulnTypeId: "security-misconfiguration",
    label: "Verbose error messages disclose internals (web app)",
    platforms: ["web"],
    description: "Unhandled errors return verbose stack traces or database error text, disclosing internal paths, library versions, or query structure — informational but useful for further attacks.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "L", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "L", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a05-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-209",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP Top 10 2021 — A05 Security Misconfiguration", url: "https://owasp.org/Top10/2021/A05_2021-Security_Misconfiguration/" },
    ],
  },
  {
    id: "sm-verbose-error-disclosure-api",
    vulnTypeId: "security-misconfiguration",
    label: "Verbose error messages disclose internals (API)",
    platforms: ["api"],
    description: "Unhandled API errors return verbose stack traces or database error text, disclosing internal paths, library versions, or query structure — informational but useful for further attacks.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "L", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "L", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api8-security-misconfiguration",
    vrtRefId: "security-misconfiguration",
    cweId: "CWE-209",
    references: [
      { label: "PortSwigger — Testing for security misconfiguration", url: "https://portswigger.net/support/using-burp-to-test-for-security-misconfiguration-issues" },
      { label: "OWASP API Security Top 10 2023 — API8 Security Misconfiguration", url: "https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/" },
    ],
  },

  // ---- insecure-deserialization ----
  {
    id: "id-java-gadget-chain-rce",
    vulnTypeId: "insecure-deserialization",
    label: "Java deserialization — gadget chain leads to RCE",
    platforms: ["web", "api", "desktop-windows", "desktop-linux"],
    description: "Untrusted data is passed to Java's native deserialization with a vulnerable library (e.g. Commons Collections) on the classpath, enabling a gadget chain to full remote code execution.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "H", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a08-software-data-integrity",
    vrtRefId: "insecure-deserialization",
    cweId: "CWE-502",
    references: [
      { label: "PortSwigger — Insecure deserialization", url: "https://portswigger.net/web-security/deserialization" },
      { label: "OWASP Cheat Sheet — Deserialization", url: "https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html" },
    ],
  },
  {
    id: "id-php-object-injection",
    vulnTypeId: "insecure-deserialization",
    label: "PHP object injection via unserialize() on user input",
    platforms: ["web", "api"],
    description: "User-controlled input reaches PHP's unserialize(), enabling a property-oriented-programming chain (e.g. to arbitrary file write or a secondary SQL injection).",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "L" },
    cvss40: { AV: "N", AC: "H", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "L", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a08-software-data-integrity",
    vrtRefId: "insecure-deserialization",
    cweId: "CWE-502",
    references: [
      { label: "PortSwigger — Insecure deserialization", url: "https://portswigger.net/web-security/deserialization" },
      { label: "OWASP Cheat Sheet — Deserialization", url: "https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html" },
    ],
  },

  // ---- xxe ----
  {
    id: "xxe-file-disclosure",
    vulnTypeId: "xxe",
    label: "XXE — local file disclosure via XML external entity",
    platforms: ["web", "api"],
    description: "An XML parser resolves external entities, letting an attacker define one that reads arbitrary local files (e.g. /etc/passwd, app config with secrets) back into the response.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a05-security-misconfiguration",
    vrtRefId: "xxe",
    cweId: "CWE-611",
    references: [
      { label: "PortSwigger — XML external entity (XXE) injection", url: "https://portswigger.net/web-security/xxe" },
      { label: "OWASP Cheat Sheet — XXE Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html" },
    ],
  },
  {
    id: "xxe-blind-oob",
    vulnTypeId: "xxe",
    label: "Blind XXE — out-of-band exfiltration, SSRF-like pivot",
    platforms: ["web", "api"],
    description: "No file contents are returned directly; data is exfiltrated via an external DTD and an out-of-band HTTP/DNS channel, which can also reach internal-only network endpoints.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "N", S: "C", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "N", VC: "L", VI: "N", VA: "N", SC: "H", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a05-security-misconfiguration",
    vrtRefId: "xxe",
    cweId: "CWE-611",
    references: [
      { label: "PortSwigger — XML external entity (XXE) injection", url: "https://portswigger.net/web-security/xxe" },
      { label: "OWASP Cheat Sheet — XXE Prevention", url: "https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html" },
    ],
  },

  // ---- path-traversal ----
  {
    id: "pt-web-lfi-read",
    vulnTypeId: "path-traversal",
    label: "Path traversal — arbitrary file read via a file parameter",
    platforms: ["web"],
    description: "A ../../../../etc/passwd-style payload in a file-loading parameter reads arbitrary files the web server process can access.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "path-traversal",
    cweId: "CWE-22",
    references: [
      { label: "PortSwigger — Directory/path traversal", url: "https://portswigger.net/web-security/file-path-traversal" },
      { label: "OWASP — Path Traversal", url: "https://owasp.org/www-community/attacks/Path_Traversal" },
    ],
  },
  {
    id: "pt-api-file-download-traversal",
    vulnTypeId: "path-traversal",
    label: "Path traversal — API file-download endpoint",
    platforms: ["api"],
    description: "An API's file-download endpoint doesn't sanitize the requested filename, permitting retrieval of arbitrary files outside the intended directory.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a01-broken-access-control",
    vrtRefId: "path-traversal",
    cweId: "CWE-22",
    references: [
      { label: "PortSwigger — Directory/path traversal", url: "https://portswigger.net/web-security/file-path-traversal" },
      { label: "OWASP — Path Traversal", url: "https://owasp.org/www-community/attacks/Path_Traversal" },
    ],
  },
  {
    id: "pt-desktop-windows-plugin-load",
    vulnTypeId: "path-traversal",
    label: "Path traversal via a malicious file/project (Windows desktop app)",
    platforms: ["desktop-windows"],
    description: "A desktop app's \"load file\"/plugin feature is vulnerable to path traversal; opening a malicious project file lets it read arbitrary files the app's process can access.",
    cvss31: { AV: "L", AC: "L", PR: "N", UI: "R", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "N", UI: "P", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "path-traversal",
    cweId: "CWE-22",
    references: [
      { label: "PortSwigger — Directory/path traversal", url: "https://portswigger.net/web-security/file-path-traversal" },
      { label: "OWASP — Path Traversal", url: "https://owasp.org/www-community/attacks/Path_Traversal" },
    ],
  },
  {
    id: "pt-desktop-mac-file-import-traversal",
    vulnTypeId: "path-traversal",
    label: "Path traversal via a malicious file/project (macOS desktop app)",
    platforms: ["desktop-mac"],
    description: "A desktop app's \"open file\"/import feature is vulnerable to path traversal; opening a malicious bundle or project file lets it read arbitrary files the app's sandboxed process can access.",
    cvss31: { AV: "L", AC: "L", PR: "N", UI: "R", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "N", UI: "P", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "path-traversal",
    cweId: "CWE-22",
    references: [
      { label: "PortSwigger — Directory/path traversal", url: "https://portswigger.net/web-security/file-path-traversal" },
      { label: "OWASP — Path Traversal", url: "https://owasp.org/www-community/attacks/Path_Traversal" },
    ],
  },
  {
    id: "pt-desktop-linux-log-viewer",
    vulnTypeId: "path-traversal",
    label: "Path traversal in a Linux app's log-viewer feature",
    platforms: ["desktop-linux"],
    description: "A locally-installed application's log-viewer feature accepts a path parameter without sanitization, letting a local low-privileged user read arbitrary files.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "U", C: "H", I: "N", A: "N" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "N", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "path-traversal",
    cweId: "CWE-22",
    references: [
      { label: "PortSwigger — Directory/path traversal", url: "https://portswigger.net/web-security/file-path-traversal" },
      { label: "OWASP — Path Traversal", url: "https://owasp.org/www-community/attacks/Path_Traversal" },
    ],
  },

  // ---- broken-authentication ----
  {
    id: "ba-weak-password-reset-web",
    vulnTypeId: "broken-authentication",
    label: "Weak password-reset flow — predictable or leaked token (web app)",
    platforms: ["web"],
    description: "The password-reset token is predictable, non-expiring, or leaked via the Referer header, letting an attacker take over any account.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a07-auth-failures",
    vrtRefId: "broken-authentication",
    cweId: "CWE-640",
    references: [
      { label: "PortSwigger — Authentication vulnerabilities", url: "https://portswigger.net/web-security/authentication" },
      { label: "OWASP Cheat Sheet — Session Management", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ba-weak-password-reset-api",
    vulnTypeId: "broken-authentication",
    label: "Weak password-reset flow — predictable or leaked token (API)",
    platforms: ["api"],
    description: "An API's password-reset token is predictable or non-expiring, letting an attacker take over any account by calling the reset endpoint directly.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api2-broken-authentication",
    vrtRefId: "broken-authentication",
    cweId: "CWE-640",
    references: [
      { label: "PortSwigger — Authentication vulnerabilities", url: "https://portswigger.net/web-security/authentication" },
      { label: "OWASP API Security Top 10 2023 — API2 Broken Authentication", url: "https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/" },
    ],
  },
  {
    id: "ba-session-fixation",
    vulnTypeId: "broken-authentication",
    label: "Session fixation — session ID not regenerated after login",
    platforms: ["web"],
    description: "The application doesn't regenerate the session ID after login, letting an attacker fixate a known session ID on the victim and hijack it once they authenticate.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "R", S: "U", C: "H", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "P", VC: "H", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a07-auth-failures",
    vrtRefId: "broken-authentication",
    cweId: "CWE-384",
    references: [
      { label: "PortSwigger — Authentication vulnerabilities", url: "https://portswigger.net/web-security/authentication" },
      { label: "OWASP Cheat Sheet — Session Management", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ba-missing-mfa-brute-force-web",
    vulnTypeId: "broken-authentication",
    label: "No rate-limiting/MFA — credential brute-forcing succeeds (web login form)",
    platforms: ["web"],
    description: "The web login form has no rate-limiting, lockout, or MFA, allowing an attacker to brute-force credentials until a weak password succeeds.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "N", S: "U", C: "H", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "N", VC: "H", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a07-auth-failures",
    vrtRefId: "broken-authentication",
    cweId: "CWE-307",
    references: [
      { label: "PortSwigger — Authentication vulnerabilities", url: "https://portswigger.net/web-security/authentication" },
      { label: "OWASP Cheat Sheet — Session Management", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ba-missing-mfa-brute-force-api",
    vulnTypeId: "broken-authentication",
    label: "No rate-limiting/MFA — credential brute-forcing succeeds (API/mobile login)",
    platforms: ["api", "mobile"],
    description: "The login API endpoint — called directly or via a mobile app — has no rate-limiting, lockout, or MFA, allowing an attacker to brute-force credentials until a weak password succeeds. The flaw lives in the backend API regardless of which client reaches it, so it's scored as an API finding even when discovered through mobile testing.",
    cvss31: { AV: "N", AC: "H", PR: "N", UI: "N", S: "U", C: "H", I: "L", A: "N" },
    cvss40: { AV: "N", AC: "H", AT: "P", PR: "N", UI: "N", VC: "H", VI: "L", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api2-broken-authentication",
    vrtRefId: "broken-authentication",
    cweId: "CWE-307",
    references: [
      { label: "PortSwigger — Authentication vulnerabilities", url: "https://portswigger.net/web-security/authentication" },
      { label: "OWASP API Security Top 10 2023 — API2 Broken Authentication", url: "https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/" },
    ],
  },

  // ---- command-injection ----
  {
    id: "ci-web-os-command-injection",
    vulnTypeId: "command-injection",
    label: "OS command injection — unsanitized input reaches a shell command",
    platforms: ["web"],
    description: "A feature that shells out (e.g. a network diagnostic \"ping\" tool) passes unsanitized user input to the OS shell, giving full remote code execution as the web server user.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "command-injection",
    cweId: "CWE-78",
    references: [
      { label: "PortSwigger — OS command injection", url: "https://portswigger.net/web-security/os-command-injection" },
      { label: "OWASP Cheat Sheet — OS Command Injection Defense", url: "https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ci-api-command-injection",
    vulnTypeId: "command-injection",
    label: "OS command injection via an API parameter (e.g. media-processing service)",
    platforms: ["api"],
    description: "A microservice shells out to a tool like ffmpeg/ImageMagick with an unsanitized filename parameter, giving full remote code execution on the processing host.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a03-injection",
    vrtRefId: "command-injection",
    cweId: "CWE-78",
    references: [
      { label: "PortSwigger — OS command injection", url: "https://portswigger.net/web-security/os-command-injection" },
      { label: "OWASP Cheat Sheet — OS Command Injection Defense", url: "https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html" },
    ],
  },
  {
    id: "ci-desktop-local-privesc",
    vulnTypeId: "command-injection",
    label: "Local privilege escalation via command injection in a privileged helper",
    platforms: ["desktop-windows", "desktop-mac", "desktop-linux"],
    description: "A low-privileged local user triggers command injection in a privileged helper process/service, escalating to SYSTEM/root.",
    cvss31: { AV: "L", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "H" },
    cvss40: { AV: "L", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: null,
    vrtRefId: "command-injection",
    cweId: "CWE-78",
    references: [
      { label: "PortSwigger — OS command injection", url: "https://portswigger.net/web-security/os-command-injection" },
      { label: "OWASP Cheat Sheet — OS Command Injection Defense", url: "https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html" },
    ],
  },

  // ---- parameter-tampering ----
  {
    id: "param-web-checkout-price-tampering",
    vulnTypeId: "parameter-tampering",
    label: "Checkout price/quantity tampering — client-supplied value trusted without server revalidation",
    platforms: ["web"],
    description: "A guest or logged-in checkout flow sends the unit price, quantity, or discount amount as a client-editable form field or hidden parameter, and the server accepts it as-is instead of recalculating it from trusted server-side data — letting an attacker buy at an arbitrary price without needing an account at all.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "N", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "N", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "web-a04-insecure-design",
    vrtRefId: "parameter-tampering",
    cweId: "CWE-472",
    references: [
      { label: "PortSwigger — Business logic vulnerabilities", url: "https://portswigger.net/web-security/logic-flaws" },
      { label: "OWASP Top 10 2021 — A04 Insecure Design", url: "https://owasp.org/Top10/2021/A04_2021-Insecure_Design/" },
    ],
  },
  {
    id: "param-api-mass-assignment-role-field",
    vulnTypeId: "parameter-tampering",
    label: "Mass assignment — undocumented \"role\"/\"isAdmin\" request field grants privilege",
    platforms: ["api"],
    description: "An API endpoint binds the entire JSON request body directly to an internal object without an allow-list, so a low-privileged authenticated user can add an undocumented property (e.g. \"role\": \"admin\") to a request and have it accepted, granting themselves elevated privileges.",
    cvss31: { AV: "N", AC: "L", PR: "L", UI: "N", S: "C", C: "H", I: "H", A: "H" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "L", UI: "N", VC: "H", VI: "H", VA: "H", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "api-api3-bopla",
    vrtRefId: "parameter-tampering",
    cweId: "CWE-915",
    references: [
      { label: "OWASP Cheat Sheet — Mass Assignment", url: "https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html" },
      { label: "OWASP API Security Top 10 2023 — API3 Broken Object Property Level Authorization", url: "https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/" },
    ],
  },
  {
    id: "param-mobile-client-side-purchase-validation",
    vulnTypeId: "parameter-tampering",
    label: "Mobile app trusts a client-supplied purchase amount/entitlement flag",
    platforms: ["mobile"],
    description: "A mobile app calculates a purchase amount or premium-feature entitlement flag on the client and sends it to the backend as a trusted value instead of the backend deriving it itself, even for anonymous/device-linked sessions with no registered account; intercepting and tampering with the app's own request (e.g. via a proxy) lets an attacker unlock paid content or pay an arbitrary amount.",
    cvss31: { AV: "N", AC: "L", PR: "N", UI: "N", S: "U", C: "N", I: "H", A: "N" },
    cvss40: { AV: "N", AC: "L", AT: "N", PR: "N", UI: "N", VC: "N", VI: "H", VA: "N", SC: "N", SI: "N", SA: "N", E: "X" },
    owaspRefId: "mobile-m4-input-output-validation",
    vrtRefId: "parameter-tampering",
    cweId: "CWE-472",
    references: [
      { label: "PortSwigger — Business logic vulnerabilities", url: "https://portswigger.net/web-security/logic-flaws" },
      { label: "OWASP Mobile Top 10 2024 — M4 Insufficient Input/Output Validation", url: "https://owasp.org/www-project-mobile-top-10/2023-risks/m4-insufficient-input-output-validation.html" },
    ],
  },
];

export const CVSS_TEMPLATES_BY_ID: Record<string, CvssTemplate> = Object.fromEntries(CVSS_TEMPLATES.map((t) => [t.id, t]));
