"use client";

/** Shared fetch wrapper for the two Worker-backed tools (Security Headers Analyzer,
 *  SPF/DKIM/DMARC Checker). Same-origin in production (`/api/...`, matches the `connect-src
 *  'self'` CSP generated by scripts/generate-csp-hashes.mjs) — only points at a separate
 *  `wrangler dev` port when running `next dev` locally, since a static export has no working
 *  `/api/*` route of its own. */

const WORKER_DEV_BASE_URL = "http://localhost:8787";

function apiBaseUrl(): string {
  return process.env.NODE_ENV === "production" ? "" : WORKER_DEV_BASE_URL;
}

export type ApiResult<T> = { ok: true; data: T } | { ok: false; error: string };

/** GETs `path` (e.g. "/api/security-headers?url=...") and parses a JSON `{ error }`-shaped
 *  failure into a friendly message — including the 429 a real edge Rate Limiting rule would
 *  return once configured (that dashboard rule isn't code, but this client already expects it). */
export async function apiGet<T>(path: string): Promise<ApiResult<T>> {
  let response: Response;
  try {
    response = await fetch(`${apiBaseUrl()}${path}`);
  } catch {
    return { ok: false, error: "Couldn't reach the server — check your connection and try again." };
  }

  if (response.status === 429) {
    return { ok: false, error: "Too many requests — wait a moment and try again." };
  }

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    return { ok: false, error: "Unexpected response from the server." };
  }

  if (!response.ok) {
    const message = typeof body === "object" && body !== null && "error" in body ? String((body as { error: unknown }).error) : "Something went wrong.";
    return { ok: false, error: message };
  }

  return { ok: true, data: body as T };
}
